config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  resources :assignments, only: [:create, :destroy]
  resources :users, only: [:index, :show]
  resources :jobs
  resources :boats 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :boat
  belongs_to :job
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :assignments, dependent: :destroy
  has_many :jobs, through: :assignments
  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :container_capacity, presence: true, numericality: { only_integer: true, greater_than: 1 }

  scope :not_assigned, ->(job) {
  	if job.boat_ids.blank?
  		Boat.all
  	else
	  	where('id NOT IN (?)', job.boat_ids)
  	end
  }
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :assignments, dependent: :destroy
  has_many :boats, through: :assignments

  validates :title, presence: true
  validates :description, presence: true, length: {minimum: 50}
  validates :cost, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1000 }
  validates :containers_needed, presence: true, numericality: { only_integer: true }

  scope :not_assigned, ->(boat) {
  	if boat.job_ids.blank?
  		Job.all
  	else
	  	where('id NOT IN (?)', boat.job_ids)
  	end
  }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :boats
	has_many :jobs
	
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, length: {minimum: 6}
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :company, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :company])
  end
   def after_sign_in_path_for(user)
        user_url(user)
   end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def create
  	# @assignment = Assignment.create(assignment_params)
  	@boat = Boat.find(assignment_params[:boat_id])
  	@job = Job.find(assignment_params[:job_id])
  	@job.boats << @boat
  	respond_to do |format|
  		@type = params[:type]
  		format.js
  	end
  end

  def destroy
    @assignment = Assignment.find(params[:id]).destroy
    respond_to do |format|
      if @assignment.destroy
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def assignment_params
  	params.require(:assignment).permit(:boat_id, :job_id)
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats = Boat.all
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = current_user.boats.new(boat_params)
    respond_to do |format|
      if @boat.save
        # local: true, redirect like normal
        format.html { redirect_to root_path }
        # remote: true
        format.js # views/boats/create.js.erb
      end
    end
  end

  def show
    @boat = Boat.find(params[:id])
  end

  def edit
    @boat = current_user.boats.find(params[:id])
  end

  def update
    @boat = current_user.boats.find(params[:id])
    @boat.update_attributes(boat_params)
    redirect_to boats_path
  end

  def destroy
    @boat = current_user.boats.find(params[:id]).destroy
    respond_to do |format|
      if @boat.destroy
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :container_capacity, :location, :image)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if user_signed_in?
    @user = current_user
    @jobs = current_user.jobs.all
    @boats = current_user.boats.all
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = current_user.jobs.find(params[:id])
  end

  def update
    @job = current_user.jobs.find(params[:id])
    @job.update_attributes(job_params)
    redirect_to jobs_path
  end

  def destroy
    @job = current_user.jobs.find(params[:id]).destroy
    respond_to do |format|
      if @job.destroy
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :origin, :destination, :cost, :containers_needed)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assignments/_boat_job.html.erb
<div class="assignment">
	<p> <%= job.title %> </p>
</div>

app/views/assignments/_job_boat.html.erb
<div class="assignment">
	<p> <%= boat.name %> <%= boat.container_capacity %> <%= link_to "remove", assignment_path(boat.id), remote: true, method: :delete, class: 'remove-assignment' %> </p>
</div>

app/views/assignments/create.html.erb
<h1>Assignments#create</h1>
<p>Find me in app/views/assignments/create.html.erb</p>

app/views/assignments/create.js.erb
<% if @type == 'job' %>
	$('#job-<%= @job.id %>').find('.assignments').prepend("<%= j render 'assignments/job_boat', boat: @boat %>")
<% else %>
	$('#boat-<%= @boat.id %>').find('.assignments').prepend("<%= j render 'assignments/boat_job', job: @job %>")
<% end %>

app/views/assignments/destroy.html.erb
<h1>Assignments#destroy</h1>
<p>Find me in app/views/assignments/destroy.html.erb</p>

app/views/boats/_boat.html.erb
<div class="col">
	<div class="boat" id="boat-<%= boat.id %>">

		<div class="card boat-card" style="width: 18rem;">
			<% if boat.image.attached? %>
				<%= image_tag boat.image, class: 'card-img-top' %>
			<% end %>
		  <div class="card-body">
		    <h5 class="card-title"><%= boat.name %></h5>
		    <p class="card-text"> <strong>Location:</strong> <%= boat.location %></p>
		    <p class="card-text"> <strong>Capacity:</strong> <%= boat.container_capacity %></p>
		    <%= form_with model: Assignment.new, class: 'assignment-select' do |f| %>
					<%= f.collection_select :job_id, Job.not_assigned(boat), :id, :title, { prompt: "Add a job" }, class: 'create-assignment' %>
					<%= f.hidden_field :boat_id, value: boat.id %>
					<%= hidden_field_tag :type, 'boat' %>
				<% end %>
				<div class="assignments">
					<% boat.jobs.each do |job| %>
						<%= render 'assignments/boat_job', job: job %>
					<% end %>
				</div>
				<%= link_to "Delete", boat, method: :delete, remote: true, class: 'delete-boat-link btn btn-success' %>
		  </div>
		</div>
	</div>
</div>

app/views/boats/_boat_form.html.erb
<div class="boat-form-wrapper margin-25">
	<h3>Add a Boat</h3>
	<%= form_with model: Boat.new, id: 'new-boat-form', data: {"parsley-validate": ''} do |f| %>
		<div class="form-group">
			<%= f.text_field :name, required: true, placeholder: 'Boat Name', class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.number_field :container_capacity, required: true, min: 1, placeholder: 'Containers', class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :image %>
			<%= f.file_field :image, class: 'form-control-file' %>
		</div>
		<div class="form-group">
			<%= f.select :location, ['Tatooine', 'Hoth', 'Coruscant', 'Naboo', 'Kamino'], {}, {class: 'form-control'} %>
		</div>
			<%= f.submit class: 'btn btn-success' %>
	<% end %>
</div>

app/views/boats/create.js.erb
// Injects JS into the page that is run immediately.

$('.boats').prepend("<%= j render @boat %>");
$('#new-boat-form').parsley().reset();

app/views/boats/destroy.js.erb
Doesnt know which delete link was clicked on

app/views/boats/edit.html.erb
<h1>Boats#edit</h1>
<p>Find me in app/views/boats/edit.html.erb</p>
<%= render 'boat_form' %>

app/views/boats/index.html.erb
<%= render 'boat_form' %>
<div class="boats">
	<%= render @boats %>
</div>

app/views/boats/new.html.erb
<h1>Boats#new</h1>
<p>Find me in app/views/boats/new.html.erb</p>
<%= render 'boat_form' %>

app/views/boats/show.html.erb
<h1>Boats#show</h1>
<p>Find me in app/views/boats/show.html.erb</p>

app/views/jobs/_job.html.erb
	<div class="job" id="job-<%= job.id %>">
		<div class="card">
		  <h5 class="card-header"><%= job.title %></h5>
		  <div class="card-body">
		    <h5 class="card-title">Job Info</h5>
		    <p class="card-text"><strong>From:</strong> <%= job.origin %> </p>
		    <p class="card-text"><strong>To:</strong>  <%= job.destination %> </p>
		    <p class="card-text"><%= job.description %></p>
		    <p class="card-text">Containers Required: <%= job.containers_needed %> </p>
		    <%= form_with model: Assignment.new, class: 'assignment-select' do |f| %>
					<%= f.collection_select :boat_id, Boat.not_assigned(job), :id, :name, { prompt: "Add a boat" }, class: 'create-assignment' %>
					<%= f.hidden_field :job_id, value: job.id %>
					<%= hidden_field_tag :type, 'job' %>
				<% end %>
				<div class="assignments">
					<% job.boats.each do |boat| %>
						<%= render 'assignments/job_boat', boat: boat, job: job %>
					<% end %>
				</div>
				<%= link_to "Delete", job, method: :delete, remote: true, class: 'btn btn-success delete-job-link' %>
		  </div>
		</div>
	</div>

	<!-- Boat.where('id NOT IN (?)', job.boat_ids) -->

app/views/jobs/_job_form.html.erb
<div class="job-form-wrapper margin-25">
	<h3> Add a Job </h3>
	<%= form_with model: Job.new, id: 'new-boat-form', data: {"parsley-validate": ''} do |f| %>
		<div class="form-group">
			<%= f.text_field :title, required: true, placeholder: 'Job Title', class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.text_area :description, required: true, minlength: 50, placeholder: 'Job Description', class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.select :origin, ['Tatooine', 'Hoth', 'Coruscant', 'Naboo', 'Kamino'], {}, {class: 'form-control'} %>
		</div>
		<div class="form-group">
			<%= f.select :destination, ['Tatooine', 'Hoth', 'Coruscant', 'Naboo', 'Kamino'], {}, {class: 'form-control'} %>
		</div>
		<div class="form-group">
			<%= f.number_field :cost, required: true, min: 1000, placeholder: 'Cost', class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.number_field :containers_needed, required: true, placeholder: 'Containers Required', class: 'form-control' %>
		</div>
			<%= f.submit class: 'btn btn-success' %>
	<% end %>
</div>

app/views/jobs/create.js.erb
$('.jobs').prepend("<%= j render @job %>");
$('#new-job-form').parsley().reset();

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>
<%= render 'job_form' %>

app/views/jobs/index.html.erb
<div class="container side-nav">
	<div class="row">
		<div class="col-sm-12 col-md-2">
			<div class="margin-25">
				<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
				  <a class="btn btn-outline-light side-nav-button active" id="v-pills-jobs-tab" data-toggle="pill" href="#v-pills-jobs" role="tab" aria-controls="v-pills-jobs" aria-selected="true">Jobs</a>
				  <a class="btn btn-outline-light side-nav-button" id="v-pills-boats-tab" data-toggle="pill" href="#v-pills-boats" role="tab" aria-controls="v-pills-boats" aria-selected="false">Boats</a>
				  <a class="btn btn-outline-light side-nav-button" id="v-pills-user-info-tab" data-toggle="pill" href="#v-pills-user-info" role="tab" aria-controls="v-pills-user-info" aria-selected="false">User</a>
		      <% if user_signed_in? %>
		        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-light side-nav-button' %>
		        
		      <% else %>
		        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-outline-light side-nav-button' %>
		        
		      <% end %>
				</div>
			</div>
		</div>
		<% if user_signed_in? %>
			<div class="col-10">
				<div class="tab-content margin-25" id="v-pills-tabContent">
				  <div class="tab-pane fade show active" id="v-pills-jobs" role="tabpanel" aria-labelledby="v-pills-jobs-tab">
						<%= render 'job_form' %>
						<div class="jobs">
							<%= render @jobs %>
						</div>
				  </div>
				  <div class="tab-pane fade" id="v-pills-boats" role="tabpanel" aria-labelledby="v-pills-boats-tab">
						<%= render '/boats/boat_form' %>
				  	<div class="container">
							<div class="boats row justify-content-center">
								<%= render @boats %>
							</div>
						</div>
				  </div>
				  <div class="tab-pane fade" id="v-pills-user-info" role="tabpanel" aria-labelledby="v-pills-user-info-tab">
				  	<div class="user-info-wrapper">
							<%= render 'users/user' %>
						</div>
				  </div>
				</div>
			</div>
			
		<% else %>
			<h1>Please sign in</h1>
		<% end %>
	</div>
</div>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>
<%= render 'job_form' %>

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shipped</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <%= link_to image_tag("home.png", class: "home") , root_path  %>
   <p class="notice alert-success"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<h1> <%= @user.first_name %> <%= @user.last_name %> </h1>
<p><strong>Email:</strong> <%= @user.email %> </p>
<p><strong>Company:</strong> <%= @user.company %> </p>
<%= link_to "Edit User", edit_user_registration_path, class: 'btn btn-success' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>